import React from "react";

import "./typewriter.css";

const CaymanTheme = () => {
  return (
    <>
      <a id="skip-to-content" href="#content">
        Skip to the content.
      </a>

      <header className="page-header" role="banner">
        <h1 className="project-name">Cayman theme</h1>
        <h2 className="project-tagline">
          Cayman is a clean, responsive theme for GitHub Pages.
        </h2>
      </header>

      <main id="content" className="main-content" role="main">
        <p>
          Text can be <strong>bold</strong>, <em>italic</em>, or
          <del>strikethrough</del>.
        </p>

        <p>
          <a href="./another-page.html">Link to another page</a>.
        </p>

        <p>There should be whitespace between paragraphs.</p>

        <h1 id="header-1">Header 1</h1>
        <p>
          This is a normal paragraph following a header. GitHub is a code
          hosting platform for version control and collaboration.
        </p>

        <h2 id="header-2">Header 2</h2>
        <blockquote>
          <p>This is a blockquote following a header.</p>
          <p>
            When something is important enough, you do it even if the odds are
            not in your favor.
          </p>
        </blockquote>

        <h3 id="header-3">Header 3</h3>
        <pre>
          <code>
            {`// Javascript code example
var fun = function lang(l) {
  dateformat.i18n = require('./lang/' + l);
  return true;
}`}
          </code>
        </pre>

        <h4 id="header-4">Header 4</h4>
        <ul>
          <li>This is an unordered list following a header.</li>
          <li>This is an unordered list following a header.</li>
        </ul>

        <h5 id="header-5">Header 5</h5>
        <ol>
          <li>This is an ordered list following a header.</li>
          <li>This is an ordered list following a header.</li>
        </ol>

        <h6 id="header-6">Header 6</h6>
        <table>
          <thead>
            <tr>
              <th>head1</th>
              <th>head two</th>
              <th>three</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>ok</td>
              <td>good swedish fish</td>
              <td>nice</td>
            </tr>
          </tbody>
        </table>

        <h3>Small image</h3>
        <img
          src="https://github.githubassets.com/images/icons/emoji/octocat.png"
          alt="Octocat"
        />

        <h3>Large image</h3>
        <img
          src="https://guides.github.com/activities/hello-world/branching.png"
          alt="Branching"
        />

        <h3>Definition List</h3>
        <dl>
          <dt>Name</dt>
          <dd>Godzilla</dd>
          <dt>Born</dt>
          <dd>1952</dd>
          <dt>Color</dt>
          <dd>Green</dd>
        </dl>

        <div>
          <a href="./typing_effect.html">Typing Effect</a>
          <p className="typewriter-effect">
            The typewriter Effect :update as needed
          </p>
          <p className="subtitle-effect">Welcome to my website!</p>
        </div>
      </main>

      <footer className="site-footer">
        <span className="site-footer-owner">
          <a href="https://github.com/pages-themes/cayman">cayman</a> is
          maintained by
          <a href="https://github.com/pages-themes">pages-themes</a>.
        </span>
        <span className="site-footer-credits">
          This page was generated by
          <a href="https://pages.github.com">GitHub Pages</a>.
        </span>
      </footer>
    </>
  );
};

export default CaymanTheme;
