name: Deploy Angular App to GitHub Pages

on:
  # push:
  # branches:
  #   - main # Change to your default branch if it's different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use a suitable Node.js version

      - name: Install Angular CLI
        run: npm install -g @angular/cli@18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --output-path=dist --base-href "/AkshayV30/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
